### ISSUE TITLE
[BUG] Data Download Tool does not allow selection of correct place type

### ISSUE THREAD

**Issue by sekmiller** [datacommonsorg/website#2745]
### Describe the bug
In the Data Download Tool the Select Place Type dropdown doesn't include the type of place selected

### To Reproduce
URL: https://gdc.dataverse.org/tools/download
Browser: Safari, Chrome

1. Go to  https://gdc.dataverse.org/tools/download
2.  Select California as a geographic area
3. Click on Select Place Type
4. See error "State" is not one of the place types available

### Expected behavior
If I select a State that should be one of the place types available in the Select Place Type dropdown

### Screenshots
Copy/pasting screenshots from the clipboard into this form works!
<img width="1022" alt="Screen Shot 2023-05-26 at 3 12 14 PM" src="https://github.com/datacommonsorg/website/assets/2364928/81f7f5c1-c8a5-43de-b772-d51afeea6e3a">

**Comment by shifucun** [comment]
This should have been fixed in our repo. Can you sync your code base and deploy it again?

**Comment by sekmiller** [comment]
I got the latest and I am still seeing this issue on our custom site. I'm also seeing it on Stanford's site https://datacommons.stanford.edu/tools/download

**Comment by sekmiller** [comment]
Closing as it looks better now. possibly user error/misinterpretation
